### ISSUE TITLE
install.sh uses '7z'-command, which is in p7zip-plugins

### ISSUE THREAD

**Issue by leahparsuidualc-zz** [m13253/clover-linux-installer#1]
To make use of your 'install.sh' wherein you use the '7z'-command, it is (at least in Fedora 26 WorkStation, KDE-Neon and Debian Stretch, to name those i checked so far) necessary to install not just 'p7zip', but also 'p7zip-plugins', which contains the '7z'-command.

Please update your README.md

**Comment by m13253** [comment]
Thank you for your report.

I did a quick search and found these:
- Debian, Ubuntu: p7zip-full
- Fedora: p7zip-plugins
- ArchLinux, openSUSE: p7zip

Since I use ArchLinux and openSUSE, I didn't realize the problem.
I will now update README.md.
