### ISSUE TITLE
Bootable flag

### ISSUE THREAD

**Issue by grafviktor** [m13253/clover-linux-installer#2]
Please mention, that except for changing file system type of partition, a user must add `Boot` flag.

**Comment by m13253** [comment]
Thank you for your response!

Would you please directly modify the README file and send me a pull request? In this way I can credit you as a contributor.

**Comment by grafviktor** [comment]
Thank you. Pr #3 has been sent.

**Comment by m13253** [comment]
Fixed in #3. Closing.

Thank you!
