### ISSUE TITLE
not enter clover bootloader after reboot

### ISSUE THREAD

**Issue by blackinitial** [m13253/clover-linux-installer#5]
i was follow intruction from readme and install successfully.
then i reboot my laptop but bootloader not change to clover still on grub2..

**Comment by m13253** [comment]
Would you please provide a complete log of your operation?

Please note that this program is for installing Clover with UEFI emulation on a non-UEFI device. If your computer already supports UEFI, please install Clover directly.

**Comment by blackinitial** [comment]
Oh I see, my laptop already UEFI mode. So I must install clover directly. 
Thanks for reply.. :)
