### ISSUE TITLE
nvme boot

### ISSUE THREAD

**Issue by millsp** [m13253/clover-linux-installer#7]
Hi @m13253,

Would you be able to give me insight about making a nvme drive bootable?

I installed ubuntu on it but clover fails to see it, is it related to the drivers?

For info, I am using a M.2 to PCIe adapter to do this on my (x58 chipset).

Thanks

**Comment by m13253** [comment]
I just did a search on the Internet: you might need to put a driver named `NvmExpressDxe` somewhere inside your EFI partition.

I am not sure whether it would work because I don't have any NVMe drive.

**Comment by millsp** [comment]
Hey @m13253, thanks! I put the driver into clover, and it did detect the ssd successfully... But then when it comes to booting nothing happens. Should the driver also sit on the ssd?

**Comment by m13253** [comment]
> But then when it comes to booting nothing happens. Should the driver also sit on the ssd?

I guess you need to enable verbose logging and see whether Linux kernel prints anything useful.
Sometimes it's just some missing boot command line arguments.
